using System.Diagnostics;
using System.Text.Json;
using Burntime.Platform;
using Burntime.Framework;
using Burntime.Platform.IO;
using Burntime.Remaster;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace Burntime.MonoGame;

internal sealed class VisualTestRunner(string outputDirectory, bool touchOnly = false) : IVisualTestRunner
{
    public string OutputDirectory { get; } = outputDirectory;
    readonly string[] names = touchOnly ? VisualTestScenes.TouchNames : VisualTestScenes.Names;
    readonly List<string> captured = [];
    readonly Stopwatch deadline = Stopwatch.StartNew();
    VisualTestScenes? scenes;
    int index = -1;
    int readyFrames;
    bool nextScene = true;
    int animationFrames;
    bool advanceAnimation;
    public bool Complete { get; private set; }

    public static int Run(string[] args)
    {
        // Deliberately small private CLI; the Python script owns the user interface.
        if (args.Length is < 3 or > 6 || args.Skip(3).Any(arg =>
            arg is not ("--native-filter" or "--language=en" or "--language=de" or "--touch")) || args[0] != "--visual-test" ||
            args[1] is not ("classic" or "newgfx" or "classic-no-hints"))
        {
            Console.Error.WriteLine("Usage: Burntime --visual-test classic|newgfx|classic-no-hints OUTPUT_DIRECTORY [--native-filter] [--language=en|--language=de] [--touch]");
            return 2;
        }
        string output = Path.GetFullPath(args[2]);
        Directory.CreateDirectory(output);
        FileSystem.UserFolderOverride = Path.Combine(output, "user");
        Directory.CreateDirectory(FileSystem.UserFolderOverride);
        int hints = (int)(args[1] == "classic-no-hints"
            ? UIHintVisibilityMode.Hide : UIHintVisibilityMode.Full);
        string language = args.Contains("--language=de") ? "de" : "en";
        System.IO.File.WriteAllText(Path.Combine(FileSystem.UserFolderOverride, "user.txt"),
            $"newgfx={(args[1] == "newgfx" ? "true" : "false")}\nprompts={hints}\nlanguage={language}\nfullscreen=false\nmusic=off\nmap_music=none\ncontroller_glyphs=xbox\n");
        Platform.Math.SetRandomSeed(123);
        VisualTestRunner runner = new(output, args.Contains("--touch"));
        try
        {
            using BurntimeGame game = new(emulateSteamDeck: true,
                nearestPointOutputFiltering: args[1] != "newgfx" && !args.Contains("--native-filter"));
            game.VisualTest = runner;
            game.Run();
            return runner.Complete ? 0 : 1;
        }
        catch (Exception exception)
        {
            System.IO.File.WriteAllText(Path.Combine(output, "error.txt"), exception.ToString());
            Console.Error.WriteLine(exception);
            return 1;
        }
        finally
        {
            FileSystem.UserFolderOverride = null;
        }
    }

    public void Update(BurntimeGame game, BurntimeClassic app)
    {
        if (Complete) return;
        if (deadline.Elapsed > TimeSpan.FromSeconds(60))
        {
            System.IO.File.WriteAllText(Path.Combine(OutputDirectory, "error.txt"),
                $"Timed out loading scenario {names[System.Math.Max(0, index)]}");
            game.Exit();
            return;
        }
        if (scenes == null)
        {
            app.VersionLabel = "visual-test";
            app.LastInputMode = InputMode.Keyboard;
            app.Process(0); // normal startup initializes the module and first scene
            scenes = new(app);
        }
        if (nextScene)
        {
            index++;
            Log.Info($"VISUAL SCENARIO: {names[index]}");
            scenes.Open(names[index]);
            nextScene = false;
            readyFrames = 0;
            animationFrames = names[index] == "menu" ? 60 : 0;
            advanceAnimation = false;
            game.MainTarget.TotalElapsed = 0;
            deadline.Restart();
        }
        // Freeze scene time except for the menu's fixed, post-load animation warmup.
        // Resource requests, GPU uploads and ordinary scene updates still run every frame.
        float elapsed = advanceAnimation && animationFrames > 0 &&
            !game.ResourceManager.IsLoading && game.LoadingStack == 0 ? 1f / 60 : 0;
        if (elapsed > 0) animationFrames--;
        app.Process(elapsed);
        game.MainTarget.Elapsed = elapsed;
        game.MainTarget.TotalElapsed += elapsed;
        game.RenderDevice.Begin();
        app.Render(game.MainTarget);
        game.RenderDevice.End();
    }

    public void Capture(BurntimeGame game)
    {
        if (Complete || index < 0) return;
        if (game.IsLoading || game.ResourceManager.IsLoading || game.LoadingStack != 0 ||
            game.BlendOverlay.BlendState != 0)
        {
            readyFrames = 0;
            return;
        }
        // Allow lazy requests and GPU uploads generated by the completed scene to settle.
        if (++readyFrames < 3) return;
        if (animationFrames > 0)
        {
            advanceAnimation = true;
            return;
        }
        var presentation = game.GraphicsDevice.PresentationParameters;
        int width = presentation.BackBufferWidth, height = presentation.BackBufferHeight;
        Color[] pixels = new Color[width * height];
        game.GraphicsDevice.GetBackBufferData(pixels);
        // The window presents the already-composited RGB values as opaque. Backbuffer
        // alpha contains blend-pass bookkeeping, not transparency for the screenshot.
        for (int i = 0; i < pixels.Length; i++)
            pixels[i].A = 255;
        using Texture2D image = new(game.GraphicsDevice, width, height);
        image.SetData(pixels);
        string name = names[index];
        using (var stream = System.IO.File.Create(Path.Combine(OutputDirectory, name + ".png")))
            image.SaveAsPng(stream, width, height);
        captured.Add(name);
        Console.WriteLine($"Captured {name}");
        nextScene = true;
        if (index + 1 == names.Length)
        {
            Complete = true;
            System.IO.File.WriteAllText(Path.Combine(OutputDirectory, "captures.json"),
                JsonSerializer.Serialize(captured));
            game.Exit();
        }
    }
}
