<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BurnGfxRipper</RootNamespace>
    <AssemblyName>BurnGfxRipper</AssemblyName>
    <StartupObject>BurnGfxRipper.Program</StartupObject>
    <IsPublishable>False</IsPublishable>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Burntime.BurnGfx\Burntime.BurnGfx.csproj" />
    <Compile Remove="SpriteSheet.cs" />
    <Compile Remove="TextureUtils.cs" />
    <Compile Remove="TileExporter.cs" />
  </ItemGroup>
</Project>
