name: main

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build
      run: (cd source && dotnet build Burntime.MonoGame -c Release && cd ..)

    - name: Package
      run: tar -caf burntime-${{ github.ref_name }}.zip -C ./bin/Release *

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: burntime
        path: burntime-${{ github.ref_name }}.zip
